nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['*']
        max_age: 3600
        allow_credentials: false

    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET', 'OPTIONS']
            allow_credentials: false
            max_age: 3600

        '^/uploads/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS']
            allow_credentials: false
            max_age: 3600

# doc : permet d'accepter toutes les origines car dart ne permet pas le crossOrigin en local. 
# ex : localhost:57850, symfo : localhost:8000
# en gros front et back ne tournent pas sur la meme chose (57850 et 8000) donc il faut autoriser le cross origin.